name: cod_soft_alarm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  alarm: ^3.1.3
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.0
  intl: ^0.19.0
  permission_handler: ^11.3.1
  simple_ripple_animation: ^0.0.9
  shared_preferences: ^2.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
  - assets/